server:
  port: 8088
  servlet:
    context-path: /userServer

logging:
  level:
    org:
      springframework:
        security: DEBUG
spring:
  data:
    mongodb:
      uri: mongodb://localhost/userServer
