server:
  port: 8088
  servlet:
    context-path: /userServer
#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG
spring:
  data:
    mongodb:
        uri: mongodb://opengms:OpenGMS2018*Collaboration@94.191.49.160:27110/userServer?authSource=userServer
#mongodb://opengms:OpenGMS2018*Collaboration@94.191.49.160:27110/userServer?authSource=userServer
#mongodb://172.21.212.103:27017/userServer
#mongodb://localhost:27017/userServer
  mail:
    host: smtp.163.com
    username: geoproblemsolving@163.com
    password: LYC123456
  #使用 jar 包方式进行部署存放文件需要映射jar外路径作为静态资源路径
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:static/,file:./static/avatar